---
# Test filter_plugins/list_filters.py

- name: list_filters
  hosts: localhost
  gather_facts: false

  vars:
    fruits: ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
    fruits_quality:
      - {name: 'orange', quality: 'A'}
      - {name: 'apple', quality: 'B'}
      - {name: 'pear', quality: 'A'}
      - {name: 'banana', quality: 'C'}
      - {name: 'kiwi', quality: 'C'}
      - {name: 'apple', quality: 'B'}
      - {name: 'banana', quality: 'A'}
    vegetables: ['potato', 'tomato', 'carrot']
    select_bool7: [false, true, true, false, false, true, false]
    students: [['john', 'A', 15], ['jane', 'B', 12], ['dave', 'B', 10]]
    dict1: {'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}
    dict2: {'k1': {'k11': 'v11'}, 'k2': {'k21': 'v21'}, 'k3': {'k31': 'v31'}}
    dict5: {'k1': {'k11': 'v11'}, 'k2': {'k21': 'v21'}, 'k3': 'v31'}
    dict3: {'k1': ['k11', 'v11'], 'k2': ['k21': 'v21'], 'k3': ['k31': 'v31']}
    dict4:
      - {'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}
      - {'l1': 'v1', 'l2': 'v2', 'l3': 'v3'}
      - {'m1': 'v1', 'm2': 'v2', 'm3': 'v3'}
    packages:
      app1:
        name: Application1
        packages: [pkg1, pkg2, pkg3]
      app2:
        name: Application2
        packages: [pkg4]
    list1: [{'k11': 'v11'}, {'k12': 'v12'}, {'k13': 'v13'}]
    list2: [{'k21': 'v21'}, {'k22': 'v22'}, {'k23': 'v23'}]
    list3: [{'k31': 'v31'}, {'k32': 'v32'}, {'k33': 'v33'}]
    list4:
      - name: myname01
        param01: myparam01
      - name: myname02
        param01: myparam02
    list5:
      - name: myname01
        param01: myparam03
      - name: myname02
        param02: myparam04
      - name: myname03
        param03: myparam03
    list4b:
      - name: myname02
        param01: myparam02
      - name: myname01
        param01: myparam01
    list4c:
      - name
      - name: myname01
        param01: myparam01
    list5b:
      - name: myname02
        param02: myparam04
      - name: myname03
        param03: myparam03
      - name: myname01
        param01: myparam03
    list6:
      - name: myname01
        param01: myparam03
      - name: myname02
        param01: myparam02
        param02: myparam04
      - name: myname03
        param03: myparam03
    ranges1: [[2], [3]]
    ranges2: [[2, 4], [11, 13], [997, 999]]
    ranges3: [[2, 8, 2], [11, 22, 3], [997, 999, 1]]
    lipsums: [[2, false, 20, 100], [4, false, 10, 50]]

  tasks:
    - debug:
        var: fruits
      tags: fruits
    - debug:
        var: fruits_quality
      tags: fruits_quality
    - debug:
        var: students
      tags: students
    - debug:
        msg: "list length: {{ fruits|length }}"
      tags: lm_length
    - debug:
        msg: "append 'tangerine': {{ fruits|list_append('tangerine') }}"
      tags: lm_append
    - debug:
        msg: "append 'vegetables': {{ fruits|list_append(vegetables) }}"
      tags: lm_append
    - debug:
        msg: "append 'vegetables' flatten: {{ fruits|
                                              list_append(vegetables)|
                                              flatten }}"
      tags: lm_append
    - debug:
        msg: "extend 'vegetables': {{ fruits|list_extend(vegetables) }}"
      tags: lm_extend
    - debug:
        msg: "insert plum at 3: {{ fruits|list_insert(3, 'plum') }}"
      tags: lm_extend
    - debug:
        msg: "remove first banana: {{ fruits|list_remove('banana') }}"
      tags: lm_remove
    - debug:
        msg: "pop 2: {{ fruits|list_pop(2) }}"
      tags: lm_pop
    - debug:
        msg: "pop last: {{ fruits|list_pop() }}"
      tags: lm_pop
    - debug:
        msg: "clear: {{ fruits|list_clear() }}"
      tags: lm_clear
    - debug:
        msg: "index of apple: {{ fruits|list_index('apple') }}"
      tags: lm_index
    - debug:
        msg: "index of apple from 3: {{ fruits|
                                        list_index('apple', 3) }}"
      tags: lm_index
    - debug:
        msg: "index of apple from 2 to 4: {{ fruits|
                                             list_index('apple', 2, 4) }}"
      tags: lm_index
    - debug:
        msg: "count apple: {{ fruits|list_count('apple') }}"
      tags: lm_count
    - debug:
        msg: "sort fruits: {{ fruits|list_sort() }}"
      tags: lm_sort
    - debug:
        msg: "sort fruits: {{ fruits|list_sort(ls_reverse=True) }}"
      tags: lm_sort_reverse
    - debug:
        msg: "sort students by grade: {{ students|list_sort_list(1) }}"
      tags: lm_sort_list_grade
    - debug:
        msg: "sort students by grade: {{ students|list_sort_list(1, ls_reverse=True) }}"
      tags: lm_sort_list_grade_reverse
    - debug:
        msg: "sort students by age: {{ students|list_sort_list(2) }}"
      tags: lm_sort_list_age
    - debug:
        msg: "sort students by age: {{ students|list_sort_list(2, ls_reverse=True) }}"
      tags: lm_sort_list_age_reverse
    - debug:
        msg: "sort fruits_quality: {{ fruits_quality|list_sort_dict('quality') }}"
      tags: lm_sort_dict
    - debug:
        msg: "sort fruits_quality: {{ fruits_quality|list_sort_dict('quality', ls_reverse=True) }}"
      tags: lm_sort_dict_reverse
    - debug:
        msg: "reverse fruits: {{ fruits|list_reverse() }}"
      tags: lm_reverse
    - debug:
        msg: "reverse sort fruits: {{ fruits|list_sort()|list_reverse() }}"
      tags: lm_reverse_sort
    - debug:
        msg: "copy fruits: {{ fruits|list_copy() }}"
      tags: lm_copy
    - debug:
        msg: "search *an* in fruits: {{ fruits|list_search('.*an.*') }}"
      tags: lm_search
    - debug:
        msg: "1st 3 random samples from fruits: {{ fruits|
                                                   unique|
                                                   list_sample(3|int) }}"
      tags: lm_sample
    - debug:
        msg: "2nd 3 random samples from fruits: {{ fruits|
                                                   unique|
                                                   list_sample(3|int) }}"
      tags: lm_sample

    - debug:
        msg: "zip: {{ fruits|
                      list_zip(vegetables) }}"
      tags: lm_zip

    - debug:
        msg: "dict_zip: {{ fruits|
                           list_dict_zip(vegetables) }}"
      tags: lm_dict_zip

    - debug:
        msg: "dict_zip_rev: {{ fruits|
                               list_dict_zip_rev(vegetables) }}"
      tags: lm_dict_zip_rev

    - debug:
        msg: "list2dict: {{ list1|zip(list2)|list_list2dict }}"
      tags: lm_list2dict
    - debug:
        msg: "list2dict: {{ list1|zip(list2)|list_list2dict|
                                  zip(list3)|list_list2dict }}"
      tags: lm_list2dict_3

    - debug:
        msg: "list_split_period: {{ fruits|list_split_period(2) }}"
      tags: lm_split_period
    - debug:
        msg: "list_split_period: {{ fruits|list_split_period(3) }}"
      tags: lm_split_period
    - debug:
        msg: "list_split_period: {{ fruits|list_split_period(4) }}"
      tags: lm_split_period

    - debug:
        msg: "list_select_list_bool: {{ select_bool7|
                                        list_select_list_bool(fruits) }}"
      tags: lm_select_list_bool
    - debug:
        msg: "list_select_list_bool: {{ select_bool7|
                                        list_select_list_bool(fruits, negative=True) }}"
      tags: lm_select_list_bool_negative

    - debug:
        msg: "range: {{ ranges1|map('list_range')|list }}"
      tags: lm_range
    - debug:
        msg: "range: {{ ranges2|map('list_range')|list }}"
      tags: lm_range
    - debug:
        msg: "range: {{ ranges3|map('list_range')|list }}"
      tags: lm_range

#     - debug:
#         msg: "{{ msg.split('\\n') }}"
#       vars:
#         msg: "wrapper: {{ lipsums|map('list_wrapper', lipsum)|list }}"
#       tags: lm_wrapper

#     - debug:
#         msg: "wrapper_comp: {{ ranges2|map('list_wrapper_comp', range)|list }}"
#       tags: lm_wrapper_comp

    - debug:
        msg: "{{ list4|lists_mergeby(list5, 'name')|list }}"
      tags: lm_mergeby

    - debug:
        msg: "{{ list4c|lists_mergeby(list5, 'name')|list }}"
      when: lm_enable_err|default(false)|bool
      tags: lm_mergeby2

    - debug:
        msg: "{{ list4|lists_mergeby(list5, 'nameX')|list }}"
      tags: lm_mergeby3

    - debug:
        msg: "{{ list4b|lists_mergeby(list5b, 'name')|list }}"
      tags: lm_mergeby4

    - debug:
        msg: "{{ [{'n': 'n1', 'p1': 'A', 'p2': 'F'},
                  {'n': 'n2', 'p2': 'B'}]|
                 lists_mergeby([{'n': 'n1', 'p1': 'C'},
                                {'n': 'n2', 'p2': 'D'},
                                {'n': 'n3', 'p3': 'E'}], 'n')|
                 list }}"
      tags: lm_mergeby5

    - debug:
        var: item
      loop: "{{ fruits|any2items }}"
      tags: lm_any2items1

    - debug:
        var: item
      loop: "{{ dict2|any2items }}"
      tags:
        - lm_any2items2
        - lm_any2items2a
    - debug:
        var: item
      loop: "{{ dict5|any2items }}"
      tags:
        - lm_any2items2
        - lm_any2items2b
    - debug:
        msg: "{{ dict2|any2items }}"
      tags:
        - lm_any2items2
        - lm_any2items2c

    - debug:
        var: item
      loop: "{{ dict2|any2items(key='dict') }}"
      tags: lm_any2items3

    - name: "lm_any2items3: Key k11 present in the dictionary"
      debug:
        var: item
      loop: "{{ dict2|any2items(key='k11') }}"
      ignore_errors: true
      tags: lm_any2items3

    - debug:
        var: item
      loop: "{{ dict2|any2items(key='k11', override=True) }}"
      tags: lm_any2items3

    - debug:
        var: item
      loop: "{{ 'x'|any2items }}"
      tags: lm_any2items5

    - debug:
        var: item
      loop: "{{ None|any2items }}"
      tags: lm_any2items6

    - debug:
        var: item
      loop: "{{ dict1|any2items }}"
      tags: lm_any2items7

    - debug:
        var: item
      loop: "{{ dict4|any2items }}"
      tags: lm_any2items8

    - debug:
        var: item
      loop: "{{ {'k1': {'k11': 'v11'}, 'k2': {'k21': 'v21'}}|any2items }}"
      tags: lm_any2items9

    - debug:
        msg: "Install {{ item }}"
      with_subelements:
        - "{{ packages.values()|list }}"
        - packages
      tags: lm_any2items10

    - debug:
        msg: "{{ list4b|list_test(list5b, 'nameX')|list }}"
      tags: lm_test

# ASSERT - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - name: test lists_meged
      assert:
        that:
          - "(list4|lists_mergeby(list5, 'name')|list|difference(list6)|length) == 0"
      tags: lm_assert_mergeby

# EOF
...
